Changed yaml files

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -15,7 +15,7 @@
 
 name: Coverage
 
-on: [push, pull_request]
+on: [push]
 
 permissions:
   contents: read
@@ -29,22 +29,74 @@ jobs:
         java: [ 8 ]
 
     steps:
+    - uses: actions/setup-python@v2
+      with:
+        python-version: '3.10'
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pandas
+        pip install numpy
+    - run: sudo apt update
+    - run: sudo apt install inotify-tools
+    - run: inotifywait -mr /home/runner/work/commons-lang/commons-lang/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
+    - run: touch starting_build_uses-checkout_32
+    - run: rm starting_build_uses-checkout_32
     - uses: actions/checkout@v3.0.2
+    - run: touch starting_build_uses-cache_33
+    - run: rm starting_build_uses-cache_33
     - uses: actions/cache@v3.0.8
       with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
           ${{ runner.os }}-maven-
+    - run: touch starting_build_SetupJDKmatrixjava_39
+    - run: rm starting_build_SetupJDKmatrixjava_39
     - name: Set up JDK ${{ matrix.java }}
       uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
         java-version: ${{ matrix.java }}
+    - run: touch starting_build_BuildwithMaven_44
+    - run: rm starting_build_BuildwithMaven_44
     - name: Build with Maven
       run: mvn -V test jacoco:report --file pom.xml --no-transfer-progress
 
+    - run: touch starting_build_UploadcoveragetoCodecov_47
+    - run: rm starting_build_UploadcoveragetoCodecov_47
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v3
       with:
         files: ./target/site/jacoco/jacoco.xml
+    - run: touch starting_finished_finished_8979874
+      if: always()
+    - run: rm starting_finished_finished_8979874
+      if: always()
+    - name: Execute py script # run file
+      if: always()
+      run: |
+        python .github/workflows/script.py
+    - name: Pushes analysis to another repository
+      if: always()
+      id: push_directory
+      uses: cpina/github-action-push-to-another-repository@main
+      env:
+        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+      with:
+        source-directory: 'optimizing-ci-builds-ci-analysis'
+        destination-github-username: 'UT-SE-Research'
+        destination-repository-name: 'ci-analyzes'
+        target-branch: '1676524822-c797686'
+        target-directory: 'commons-lang/.github/workflows/coverage/build_java_${{ matrix.java }}'
+      continue-on-error: true
+    - name: Check push directory exit code
+      if: steps.push_directory.outcome == 'failure'
+      run: |
+        echo 'push failed, trying pull and then push'
+        git fetch
+        git merge origin/1676524822-c797686
+        while ! git push origin 1676524822-c797686; do
+          git fetch
+          git merge origin/1676524822-c797686
+        done
